### ISSUE TITLE
BufferNode looping and ended_count don't work as expected in python

### ISSUE THREAD

**Issue by roelvdwal** [libaudioverse/libaudioverse#33]
When checking the value of looping on a buffer node, I get the following in python 2.7.12, if looping is false:
BooleanProperty False
This, however, does always compare to True when converting it to a boolean. Ended_count seems to suffer the same problem, but when converting it with int() does work, only print statements are affected. This is after setting the looping property manually to false. When looping is true, printing it gives
BooleanProperty True. Then converting it to a normal python boolean is accurate.

**Comment by roelvdwal** [comment]
So apparently I might have opened this issue just a bit too soon, since I didn't remember that in the examples b.mul.value was used. This does work properly, So this issue might more be an enhancement to improve the documentation on this subject rather than a bug.

**Comment by camlorn** [comment]
I'm not sure what you're trying to say.  Is `bool(n.looping)` always returning true even when `looping` is false?
It looks like maybe we don't implement `__nonzero__` and `__bool__`, so this might be an easy fix if I'm understanding the bug correctly.

**Comment by camlorn** [comment]
Somehow I also missed your second comment. `.value` is optional now.  I need to go through the manual and find out where it's still listing that, but tbh I need to go through the manual and check a bunch of other stuff too, so I'm kind of trying to hold off and do it all at once.

**Comment by roelvdwal** [comment]
I do still need to use value on the looping property when compairing,
with libaudioverse 0.9a12, with setting I can omit .value, but when
compairing it will always compare to true even if it is False when
reading looping.value. I know the automating properties section has a
line modifying mul with the old sintax. .value is not required on ints
though, those compare just fine.

2017-03-27 16:37 GMT+02:00, Austin Hicks <notifications@github.com>:

**Comment by camlorn** [comment]
I suspect there is a language barrier here.  The problem is this?

```
>>> import libaudioverse
>>> libaudioverse.initialize()
>>> s=libaudioverse.Server()
>>> n=libaudioverse.BufferNode(s)
>>> if n.looping:    print("True")
...
True
```

That's obviously problematic, but I'm not sure if it's the problem you're trying to report.

**Comment by camlorn** [comment]
I'll get to this when I do the next round of small fixes.  It isn't forgotten, and it's easy enough to do, but it has to be part of the next release.

**Comment by camlorn** [comment]
Okay, done.  I found like 4 other Python bindings bugs in corner cases that no one noticed.  There'll be a new alpha in like 20 minutes once the CI server finishes that hits all of them.
